### ISSUE TITLE
Every page, it's color pallete!?

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [CodeClickers/codeclickers.github.io#1]
Hey! Isn't it a coincidence that I create the first issue on all of our GitHub projects? And also use the opportunity to mention @Luck24, so you can read this? 🤣🤣🤣

Anyway, I will get straight into the point! I want to propose and idea for our website. For now, as you know, all the pages are this light-green color, which is nice (ngl) but also a little boring. I came up with this when I was wanting to create a new page for our Rocket game. I wanted the background to fit the icons, text, etc...
So, what do you think of the following color scheme:

- ![#aaaaaa](https://via.placeholder.com/15/aaaaaa/000000?text=+) ` Home`

- ![#7AB162](https://via.placeholder.com/15/7AB162/000000?text=+) ` 365 Facts`

- ![#33ffff](https://via.placeholder.com/15/33ffff/000000?text=+) ` Rocket`

- ![#ff5500](https://via.placeholder.com/15/ff5500/000000?text=+) ` Contact`

- ![#00ff55](https://via.placeholder.com/15/00ff55/000000?text=+) ` About Us`

- ![#0055ff](https://via.placeholder.com/15/0055ff/000000?text=+) ` Donate`

Or you want other colors?

**Comment by Luck24** [comment]
Yeah! Indeed it is a coincidence @YarostheLaunchpadder 🤣

I love the idea but I would change a little bit the color scheme;

- Home 🏡: White or Grey
- 365 Facts 🔢: Green (like the UI of the App)
- Rocket 🚀: Blue (like the UI of the App)
- Contact 📞: Red (like Google.com)
- About us 🚻: Navy Blue
- Donate 💸: Yellow (like Google.com)

If the colors mentioned above are too "powerful" we should use the same colors but "lighter" (more pastel)

**Comment by YarostheLaunchpadder** [comment]
Agreed! I will use these colors then! 
#perfect 👍🏻
